apiVersion: apps/v1
kind: Deployment
metadata:
  name: replit-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: replit-app
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"