          name: Data Product CI/CD

          on:
            push:
              branches: [ main ]
            pull_request:
              branches: [ main ]

          jobs:
            test:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v3

                - name: Set up Python
                  uses: actions/setup-python@v4
                  with:
                    python-version: '3.10'
                    cache: 'pip'

                - name: Install dependencies
                  run: |
                    python -m pip install --upgrade pip
                    pip install poetry
                    poetry config virtualenvs.create false
                    poetry install

                - name: Run tests
                  run: pytest

            build-and-push:
              needs: test
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v3

                - name: Extract metadata from yaml
                  id: metadata
                  run: |
                    DOMAIN=$(grep -oP 'domain: \K.*' metadata.yaml)
                    NAME=$(grep -oP 'name: \K.*' metadata.yaml | head -1)
                    echo "domain=$DOMAIN" >> $GITHUB_OUTPUT
                    echo "name=$NAME" >> $GITHUB_OUTPUT

                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v2

                - name: Login to container registry
                  uses: docker/login-action@v2
                  with:
                    registry: ${{ secrets.REGISTRY_URL }}
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_PASSWORD }}

                - name: Build and push Docker image
                  uses: docker/build-push-action@v4
                  with:
                    context: .
                    push: true
                    tags: |
                      ${{ secrets.REGISTRY_URL }}/${{ steps.metadata.outputs.domain }}/${{ steps.metadata.outputs.name }}:${{ github.sha }}
                      ${{ secrets.REGISTRY_URL }}/${{ steps.metadata.outputs.domain }}/${{ steps.metadata.outputs.name }}:latest

                - name: Update Kubernetes manifests
                  run: |
                    sed -i "s|image:.*|image: ${{ secrets.REGISTRY_URL }}/${{ steps.metadata.outputs.domain }}/${{ steps.metadata.outputs.name }}:${{ github.sha }}|g" k8s/deployment.yaml

                - name: Commit and push updated manifests
                  uses: stefanzweifel/git-auto-commit-action@v4
                  with:
                    commit_message: "Update image to ${{ github.sha }}"
                    file_pattern: k8s/deployment.yaml